name: "Notify"

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to webhook
        env:
          WEBHOOK_URL: ${{ secrets.REDEPLOY_URL }}
        run: |
          curl -X POST -s -o /dev/null -w "%{http_code}" "$WEBHOOK_URL"